name: "send to slack"
description: ""
author: "leechungkyu"
branding:
  icon: message-square
  color: yellow

inputs:
  slack_url:
    description: "slack incoming url"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
