name: When a push occurs in the master branch, a slack alarm is generated.
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: notify
        id: notify
        
        uses: leechungkyu/send-to-slack-action@master
        with:
          slack_url: ${{ secrets.SLACK_URL }}
      
      - name : Run
        run: |
          echo 'Run!'